source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'XJPopup_Example', :exclusive => true do
  pod "XJPopup", :path => "../"
end

target 'XJPopup_Tests', :exclusive => true do
  pod "XJPopup", :path => "../"

  
end
